name: 'Build, test, and lint'
description: 'pnpm run build, test, and lint scripts'
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - uses: pnpm/action-setup@v2.2.2
      with:
        version: 7

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'pnpm'

    - name: Build, test, and lint
      run: action.sh
      shell: bash
